### PR TITLE
fix: site footer compilation errors

### PR DESCRIPTION
**Pull request by agurtovoy**
## What/Why?

Fix `site-footer.client.tsx` compilation errors (broken by changes in https://github.com/bigcommerce/catalyst/pull/2281):

typecheck errors

## Testing

Screenshot 2025-05-14 at 6 27 30 PM

### CODE REVIEW

File: core/lib/makeswift/components/site-footer/site-footer.client.tsx [hunk 1]
```diff
@@ -63,21 +65,18 @@ function combineSections(
   );
 }
 
-export const MakeswiftFooter = forwardRef(
```
Comment (agurtovoy) [inline core/lib/makeswift/components/site-footer/site-footer.client.tsx:66]: Removed `forwardRef` as the Soul's `Footer` component does not forward `ref` anymore (which is okay since it was previously simply forwarding the ref to the root element).

Comment (agurtovoy) [reply core/lib/makeswift/components/site-footer/site-footer.client.tsx:66]: The diffs are best reviewed with "Hide whitespace" toggle on.

File: core/lib/makeswift/components/site-footer/site-footer.client.tsx [hunk 2]
```diff
@@ -63,21 +65,18 @@ function combineSections(
...
-        sections={combineSections(passedProps.sections, sections)}
-      />
-    );
-  },
-);
+  return (
+    <Footer
+      {...passedProps}
+      copyright={copyright ?? passedProps.copyright}
+      logo={logo.show ? logoObject : null}
```
Comment (agurtovoy) [inline core/lib/makeswift/components/site-footer/site-footer.client.tsx:76]: `undefined` -> `null` to satisfy the current prop definition.

File: core/vibes/soul/sections/footer/index.tsx [hunk 3]
```diff
@@ -32,7 +32,7 @@ interface ContactInformation {
 }
 
 export interface FooterProps {
-  logo: Streamable<string | Image>;
+  logo: Streamable<string | Image | null>;
```
Comment (agurtovoy) [inline core/vibes/soul/sections/footer/index.tsx:35]: Allow `null`s (as does the `<Logo>` component itself).

File: core/vibes/soul/primitives/logo/index.tsx [hunk 4]
```diff
@@ -32,33 +32,35 @@ export function Logo({ className, logo: streamableLogo, href, width, height, lab
...
-            typeof logo === 'string' && (
-              <span className="font-[family-name:var(--logo-font-family,var(--font-family-heading))] text-lg leading-none font-semibold text-[var(--logo-text,hsl(var(--foreground)))] @xl:text-2xl">
-                {logo}
-              </span>
-            )
-          )}
-        </Link>
-      )}
+      {(logo) =>
+        logo !== null && (
```
Comment (agurtovoy) [inline core/vibes/soul/primitives/logo/index.tsx:36]: Do not render anything if the logo is `null`.

### Before

empty logo space

### After

no space

Comment (fikrikarim) [reply core/vibes/soul/primitives/logo/index.tsx:36]: Do we need to bring back the changes to the vibes repo?

**Review by fikrikarim — APPROVED** [review]

**Review by chanceaclark — APPROVED** [review]

File: core/vibes/soul/primitives/logo/index.tsx (hunk 4 above)
Comment (agurtovoy) [reply core/vibes/soul/primitives/logo/index.tsx]: We do, also I realized that this needs to be fixed in `canary`, too, so I'm going to move this to its own PR.
